default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dibook_development

test:
  <<: *default
  database: dibook_test

staging:
  <<: *default
  database: dibook_staging


