# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f1320d0eba7e63c462cb54399369e2cf43834403884f339bd8c31b32c0825c94612cc818d9a344b5a2af9090cf8ad4ceaffa96abdeb98904dc610106974556e

test:
  secret_key_base: 06290200e7a3af993c81007db6f68f1e5567c0662edaca527274677b1a146b80d3e3e1d0033180e182a96a0886b41280604243a4511d83878c71b20b12cf32b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
